### PR TITLE
Bond based potentials implementation

### PR DESCRIPTION
**Pull request by cortner**
transferred from previous PR #3

### CODE REVIEW

**Comment by cortner** [comment]
OK - this looks in principle ready to merge. Do we merge now or after more testing.

**Comment by cortner** [comment]
I also believe there are still performance problems. But I'll need more time to sort those out.

**Comment by cortner** [comment]
I fixed the worst performance bugs. There are more, but I think this is enough to start testing. @zhanglw0521  - unless you have any more thoughts or concerns I'll merge this and then tag this as 0.0.1

**Comment by zhanglw0521** [comment]
Thanks! It would be great if it is merged. I can then directly use ACEbonds more freely on ACEhamiltonian.

**Comment by cortner** [comment]
tagged as 0.0.2

**Pull request merged**
